#cloud-config
# add default user
users:
  - name: user
    primary_group: user
    groups: users, admin, cdrom, floppy, audio, video, plugdev, kvm, netdev, sudo
    shell: /bin/bash
    # plain_text_passwd: 'ubuntu'
    passwd: $6$UbM29R6vsMA00IzS$X64ifYxzmSF89ekm2S2M0z35C9z2gA/KT9GvwK4NLc4kz9hZBepssIHMPBn9Xk14TVCviolkENKTCThTTGwdh/
    sudo: ALL=(ALL) NOPASSWD:ALL    # enable paswordless sudo access
    lock_passwd: false              # enable password login
    no_user_group: false            # create home directory

hostname: gns3vm    # set device hostname
ssh_pwauth: True    # enable ssh password authentication

# update mirrors on first boot
package_update: true
# install all required packages
packages:
  - xfce4
  - lightdm
# - libpam-kwallet4
# - libpam-kwallet5
  - libxfce4ui-utils
  - xfce4-appfinder
  - xfce4-panel
  - xfce4-pulseaudio-plugin
  - xfce4-whiskermenu-plugin
  - xfce4-session
  - xfce4-settings
  - xfce4-terminal
  - xfconf
  - xfdesktop4
  - xfwm4
  - adwaita-qt
  - qt5ct
  - geany
  - thunar
# - midori
  # vnc tools
  - x11vnc
  - novnc